vlei-media-type =
  "application/cesr+json;profile=urn:vlei:leid" /
  "application/cesr+json;profile=urn:vlei:ecr" /
  "application/cesr+json;profile=urn:vlei:ecr;charset=utf-16le" /
  "application/cesr+json;profile=urn:vlei:oor" /
  "application/cesr+json;profile=urn:vlei:ecra" /
  "application/cesr+json;profile=urn:vlei:qvi" /
  "application/cesr+json;profile=urn:vlei:oora" /
  "application/cesr+json;profile=urn:vlei:oora;encoding=base64uri" /
  "application/cesr+cbor;profile=urn:vlei:leid" /
  "application/cesr+cbor;profile=urn:vlei:leid;encoding=text" /
  "application/cesr+cbor;profile=urn:vlei:ecr" /
  "application/cesr+cbor;profile=urn:vlei:ecr;encoding=base64uri" /
  "application/cesr+cbor;profile=urn:vlei:ecr;encoding=text" /
  "application/cesr+cbor;profile=urn:vlei:oor" /
  "application/cesr+cbor;profile=urn:vlei:oor;encoding=text" /
  "application/cesr+cbor;profile=urn:vlei:ecra" /
  "application/cesr+cbor;profile=urn:vlei:ecra;encoding=text" /
  "application/cesr+cbor;profile=urn:vlei:qvi" /
  "application/cesr+cbor;profile=urn:vlei:qvi;encoding=text" /
  "application/cesr+cbor;profile=urn:vlei:oora" /
  "application/cesr+cbor;profile=urn:vlei:oora;encoding=text" /
  "application/cesr+msgpk;profile=urn:vlei:leid" /
  "application/cesr+msgpk;profile=urn:vlei:leid;encoding=text" /
  "application/cesr+msgpk;profile=urn:vlei:ecr" /
  "application/cesr+msgpk;profile=urn:vlei:ecr;encoding=text" /
  "application/cesr+msgpk;profile=urn:vlei:oor" /
  "application/cesr+msgpk;profile=urn:vlei:oor;encoding=text" /
  "application/cesr+msgpk;profile=urn:vlei:ecra" /
  "application/cesr+msgpk;profile=urn:vlei:ecra;encoding=text" /
  "application/cesr+msgpk;profile=urn:vlei:qvi" /
  "application/cesr+msgpk;profile=urn:vlei:qvi;encoding=text" /
  "application/cesr+msgpk;profile=urn:vlei:oora" /
  "application/cesr+msgpk;profile=urn:vlei:oora;encoding=text" /
  "application/cesr;profile=urn:vlei:leid" /
  "application/cesr;profile=urn:vlei:leid;encoding=binary" /
  "application/cesr;profile=urn:vlei:leid;encoding=base64uri" /
  "application/cesr;profile=urn:vlei:leid;charset=utf-16le" /
  "application/cesr;profile=urn:vlei:ecr" /
  "application/cesr;profile=urn:vlei:ecr;encoding=binary" /
  "application/cesr;profile=urn:vlei:oor" /
  "application/cesr;profile=urn:vlei:oor;encoding=binary" /
  "application/cesr;profile=urn:vlei:ecra" /
  "application/cesr;profile=urn:vlei:ecra;encoding=binary" /
  "application/cesr;profile=urn:vlei:qvi" /
  "application/cesr;profile=urn:vlei:qvi;bencoding=binary" /
  "application/cesr;profile=urn:vlei:oora" /
  "application/cesr;profile=urn:vlei:oora;encoding=binary" 

