vlei-media-type =
  "application/acdc+json;profile=urn:vlei:leid" /
  "application/acdc+json;profile=urn:vlei:leid;charset=utf-8" /
  "application/acdc+json;profile=urn:vlei:ecr" /
  "application/acdc+json;profile=urn:vlei:ecr;charset=utf-8" /
  "application/acdc+json;profile=urn:vlei:oor" /
  "application/acdc+json;profile=urn:vlei:oor;charset=utf-8" /
  "application/acdc+json;profile=urn:vlei:lar" /
  "application/acdc+json;profile=urn:vlei:lar;charset=utf-8" /
  "application/acdc+json;profile=urn:vlei:qvi" /
  "application/acdc+json;profile=urn:vlei:qvi;charset=utf-8" /
  "application/acdc+json;profile=urn:vlei:vra" /
  "application/acdc+json;profile=urn:vlei:vra;charset=utf-8" /
  "application/acdc+cbor;profile=urn:vlei:leid" /
  "application/acdc+cbor;profile=urn:vlei:leid;base64=true" /
  "application/acdc+cbor;profile=urn:vlei:ecr" /
  "application/acdc+cbor;profile=urn:vlei:ecr;base64=true" /
  "application/acdc+cbor;profile=urn:vlei:oor" /
  "application/acdc+cbor;profile=urn:vlei:oor;base64=true" /
  "application/acdc+cbor;profile=urn:vlei:lar" /
  "application/acdc+cbor;profile=urn:vlei:lar;base64=true" /
  "application/acdc+cbor;profile=urn:vlei:qvi" /
  "application/acdc+cbor;profile=urn:vlei:qvi;base64=true" /
  "application/acdc+cbor;profile=urn:vlei:vra" /
  "application/acdc+cbor;profile=urn:vlei:vra;base64=true" /
  "application/acdc+msgpk;profile=urn:vlei:leid" /
  "application/acdc+msgpk;profile=urn:vlei:leid;base64=true" /
  "application/acdc+msgpk;profile=urn:vlei:ecr" /
  "application/acdc+msgpk;profile=urn:vlei:ecr;base64=true" /
  "application/acdc+msgpk;profile=urn:vlei:oor" /
  "application/acdc+msgpk;profile=urn:vlei:oor;base64=true" /
  "application/acdc+msgpk;profile=urn:vlei:lar" /
  "application/acdc+msgpk;profile=urn:vlei:lar;base64=true" /
  "application/acdc+msgpk;profile=urn:vlei:qvi" /
  "application/acdc+msgpk;profile=urn:vlei:qvi;base64=true" /
  "application/acdc+msgpk;profile=urn:vlei:vra" /
  "application/acdc+msgpk;profile=urn:vlei:vra;base64=true" /
  "application/acdc+cesr;profile=urn:vlei:leid" /
  "application/acdc+cesr;profile=urn:vlei:leid;base64=true" /
  "application/acdc+cesr;profile=urn:vlei:leid;charset=utf-8" /
  "application/acdc+cesr;profile=urn:vlei:ecr" /
  "application/acdc+cesr;profile=urn:vlei:ecr;base64=true" /
  "application/acdc+cesr;profile=urn:vlei:ecr;charset=utf-8" /
  "application/acdc+cesr;profile=urn:vlei:oor" /
  "application/acdc+cesr;profile=urn:vlei:oor;base64=true" /
  "application/acdc+cesr;profile=urn:vlei:oor;charset=utf-8" /
  "application/acdc+cesr;profile=urn:vlei:lar" /
  "application/acdc+cesr;profile=urn:vlei:lar;base64=true" /
  "application/acdc+cesr;profile=urn:vlei:lar;charset=utf-8" /
  "application/acdc+cesr;profile=urn:vlei:qvi" /
  "application/acdc+cesr;profile=urn:vlei:qvi;base64=true" /
  "application/acdc+cesr;profile=urn:vlei:qvi;charset=utf-8" /
  "application/acdc+cesr;profile=urn:vlei:vra" /
  "application/acdc+cesr;profile=urn:vlei:vra;base64=true" /
  "application/acdc+cesr;profile=urn:vlei:vra;charset=utf-8" /
  "application/said+json;profile=urn:vlei:leid" /
  "application/said+json;profile=urn:vlei:leid;charset=utf-8" /
  "application/said+json;profile=urn:vlei:ecr" /
  "application/said+json;profile=urn:vlei:ecr;charset=utf-8" /
  "application/said+json;profile=urn:vlei:oor" /
  "application/said+json;profile=urn:vlei:oor;charset=utf-8" /
  "application/said+json;profile=urn:vlei:lar" /
  "application/said+json;profile=urn:vlei:lar;charset=utf-8" /
  "application/said+json;profile=urn:vlei:qvi" /
  "application/said+json;profile=urn:vlei:qvi;charset=utf-8" /
  "application/said+json;profile=urn:vlei:vra" /
  "application/said+json;profile=urn:vlei:vra;charset=utf-8" /
  "application/said+cbor;profile=urn:vlei:leid" /
  "application/said+cbor;profile=urn:vlei:leid;base64=true" /
  "application/said+cbor;profile=urn:vlei:ecr" /
  "application/said+cbor;profile=urn:vlei:ecr;base64=true" /
  "application/said+cbor;profile=urn:vlei:oor" /
  "application/said+cbor;profile=urn:vlei:oor;base64=true" /
  "application/said+cbor;profile=urn:vlei:lar" /
  "application/said+cbor;profile=urn:vlei:lar;base64=true" /
  "application/said+cbor;profile=urn:vlei:qvi" /
  "application/said+cbor;profile=urn:vlei:qvi;base64=true" /
  "application/said+cbor;profile=urn:vlei:vra" /
  "application/said+cbor;profile=urn:vlei:vra;base64=true" /
  "application/said+msgpk;profile=urn:vlei:leid" /
  "application/said+msgpk;profile=urn:vlei:leid;base64=true" /
  "application/said+msgpk;profile=urn:vlei:ecr" /
  "application/said+msgpk;profile=urn:vlei:ecr;base64=true" /
  "application/said+msgpk;profile=urn:vlei:oor" /
  "application/said+msgpk;profile=urn:vlei:oor;base64=true" /
  "application/said+msgpk;profile=urn:vlei:lar" /
  "application/said+msgpk;profile=urn:vlei:lar;base64=true" /
  "application/said+msgpk;profile=urn:vlei:qvi" /
  "application/said+msgpk;profile=urn:vlei:qvi;base64=true" /
  "application/said+msgpk;profile=urn:vlei:vra" /
  "application/said+msgpk;profile=urn:vlei:vra;base64=true" /
  "application/said+cesr;profile=urn:vlei:leid" /
  "application/said+cesr;profile=urn:vlei:leid;base64=true" /
  "application/said+cesr;profile=urn:vlei:leid;charset=utf-8" /
  "application/said+cesr;profile=urn:vlei:ecr" /
  "application/said+cesr;profile=urn:vlei:ecr;base64=true" /
  "application/said+cesr;profile=urn:vlei:ecr;charset=utf-8" /
  "application/said+cesr;profile=urn:vlei:oor" /
  "application/said+cesr;profile=urn:vlei:oor;base64=true" /
  "application/said+cesr;profile=urn:vlei:oor;charset=utf-8" /
  "application/said+cesr;profile=urn:vlei:lar" /
  "application/said+cesr;profile=urn:vlei:lar;base64=true" /
  "application/said+cesr;profile=urn:vlei:lar;charset=utf-8" /
  "application/said+cesr;profile=urn:vlei:qvi" /
  "application/said+cesr;profile=urn:vlei:qvi;base64=true" /
  "application/said+cesr;profile=urn:vlei:qvi;charset=utf-8" /
  "application/said+cesr;profile=urn:vlei:vra" /
  "application/said+cesr;profile=urn:vlei:vra;base64=true" /
  "application/said+cesr;profile=urn:vlei:vra;charset=utf-8"

