; =====================================================================
; --- SATP Message (Entry Point) ---
; =====================================================================
start = satp-message